general:
  # Should the plugin check for updates?
  updates:
    check: true
    # Automatically download & install?
    download: false
    # Automatically download & install on startup?
    download_startup: false

  # Should the plugin output some useful information when scanning for blocks?
  debug: false

  # Max tiles in a chunk (Default: 256) -1 to disable
  # A chunk is defined as width x length x height blocks (16 x 16 x 256).
  limit: 256

  async:
    # Should we scan custom defined block limits asynchronously?
    # Please note: there may be bugs when enabling this feature; test thoroughly!
    # Support is enabled for this feature, if you come across any incompatibility, please report!
    enabled: true

    # Some plugins may prefer Insights to scan particular blocks synchronously,
    # so all blocks in this list will cause Insights to scan synchronously.
    # You can change the list to blacklist / whitelist mode if you prefer to.
    whitelist: false
    blocks:
      #- "HOPPER"

  # Worlds in which the live-tile-scanning feature should be enabled/disabled
  # Values are regex matched
  worlds:
    # Blacklist mode = false
    # Whitelist mode = true
    whitelist: true
    list:
      - "world"
      - "world_nether"
      - "world_the_end"

  # Regions in which the live-tile-scanning feature should be enabled/disabled
  # Values are regex matched
  regions:
    # Blacklist mode = false
    # Whitelist mode = true
    whitelist: false
    list:
      - "region1"

  # Customize the blocks which may be placed inside regions!
  region_blocks:
    # This will disallow DIAMOND_ORE placements inside region all regions starting with 'region-'
    "region1":
      # Blacklist mode = false
      # Whitelist mode = true
      whitelist: false
      regex: "region-.*"
      list:
        - "DIAMOND_ORE"
    # This will only allow DIAMOND_ORE placements inside region 'region2'
    region2:
      whitelist: true
      regex: "region2"
      list:
        - "DIAMOND_ORE"

  # Configure how Insights will work with WorldEdit
  # Please note: this only works on WorldEdit v7+.
  # This is due to the fact WorldEdit removed support for
  # legacy versions.
  worldedit:
    enabled: true
    # Replace the blocks which have a limit or leave them unchanged!
    # Possible values: REPLACEMENT, UNCHANGED
    type: "REPLACEMENT"
    replacement: "BEDROCK"

  notification:
    # How we inform the player about the live-tile count
    # Possible values are "ACTIONBAR", "BOSSBAR"
    # Default: "BOSSBAR"
    #
    # Please note: bossbar is only on Minecraft versions greater than or equal to 1.9!
    type: "BOSSBAR"

    bossbar:
      # Bossbar color
      # Possible values are "BLUE", "GREEN", "PINK", "PURPLE", "RED", "WHITE", "YELLOW"
      # Default: "BLUE"
      color: "BLUE"

      # Bossbar style
      # Possible values are "SOLID", "SEGMENTED_6", "SEGMENTED_10", "SEGMENTED_12", "SEGMENTED_20"
      # Default: "SEGMENTED_10"
      style: "SEGMENTED_10"

      # Bossbar flags
      # Possible values are "DARKEN_SKY", "PLAY_BOSS_MUSIC", "CREATE_FOG"
      # Default: []
      flags: [] # Remove [] to addCompletableFuture values
      #  - "DARKEN_SKY"
      #  - "PLAY_BOSS_MUSIC"

      # Bossbar duration before it should disappear in ticks
      # 1 second = 20 ticks
      duration: 60

  # Send notification when scanning in actionbar/bossbar
  scan_notification: true

  # If limit is disabled (= -1), should we still show the bossbar/actionbar
  # for tile entities? If set to false, this will still show the bossbar or
  # actionbar for custom defined blocks.
  always_show_notification: true

  # List with values to make Insights "passive" about it. If it is in the list,
  # players will need the permission insights.check.passive.<value> to be
  # notified about it. It will stil enable limiting, but just won't show up as
  # a message in chat. All possible values are commented out (disabled by default)
  passive:
    #- "block"
    #- "entity"
    #- "region"
    #- "tile"


  # Scanradius default radius (which will appear in tabcomplete)
  # Default: 5
  scanradius_default: 5

  limits:

    # This is a list in which order we should check limits
    # The first in the list will be first checked, last in the list checked at last, etc.
    priorities:
      - "groups"
      - "permissions"
      - "materials"
      - "entities"

    # Limits a single block in a chunk
    materials:
      # Format:
      # BLOCK: LIMIT
      DIAMOND_ORE: 128
      ENCHANTING_TABLE: 16 # If on < 1.13 use "ENCHANTMENT_TABLE"

    # Limits entities per chunk
    entities:
      CREEPER: 4

    # Set a limit to custom blocks in a chunk for certain material groups
    # This group will act as a whole limit. All blocks will count towards the limit.
    # Please note that this will override the global materials limit.
    groups:

      # Example of such a group, make sure the following line is unique!
      my_redstone_group:
        name: "Redstone"
        limit: 50
        # Bypass permission
        permission: "insights.materialgroups.bypass.redstone"
        materials:
         - "REDSTONE_WIRE"
         - "REDSTONE_BLOCK"
         - "HOPPER"
         - "DISPENSER"
         - "DROPPER"
         - "TRIPWIRE_HOOK"
         - "REDSTONE_LAMP"
         - "REDSTONE_LAMP_ON"
         - "REDSTONE_LAMP_OFF"
         - "STICKY_PISTON"
         - "STICKY_PISTON_BASE"
         - "PISTON"
         - "PISTON_BASE"
         - "REDSTONE_TORCH"
         - "TNT"
         - "NOTE_BLOCK"
         - "LEVER"
         - "REPEATER"
         - "DIODE"
         - "REDSTONE_COMPARATOR"
         - "COMPARATOR"

    # Set a limit to custom blocks in a chunk for certain groups
    # Please note that this will override the global materials limit.
    permissions:

      # Example of such a group, make sure the following line is unique!
      my_permission_group1:
        name: "Permission Group"
        # Bypass permission
        permission: "insights.permissiongroups.group1"
        materials:
          DIAMOND_BLOCK: 256
          ENCHANTING_TABLE: 32
        entities:
          CREEPER: 5
