general:
  # Max tiles in a chunk (Default: 256) -1 to disable
  # A chunk is defined as width x length x height blocks (16 x 16 x 256).
  limit: 256

  # Set a limit to custom blocks in a chunk
  # Bypass with e.g. 'insights.bypass.DIAMOND_ORE' permission
  materials:
    # Format:
    # MATERIAL: LIMIT
    DIAMOND_ORE: 128
    ENCHANTING_TABLE: 16