general:
  # Max tiles in a chunk (Default: 256) -1 to disable
  # A chunk is defined as width x length x height blocks (16 x 16 x 256).
  limit: 256

  # Set a limit to custom blocks in a chunk
  # Bypass with e.g. 'blocklimiter.bypass.DIAMOND_ORE' permission
  materials:
    # Format:
    # MATERIAL: LIMIT
    DIAMOND_ORE: 128
    ENCHANTING_TABLE: 16


messages:
  # Message send when a user tries to place more tiles than the above value
  limit_reached: "&cYou have reached the limit of 256 tiles in this chunk. Please remove some."

  # Message send when a user tries to place more custom defined limited blocks
  # Special placeholders:
  # %limit%
  # %material%
  limit_reached_custom: "&cYou have reached the limit of %limit%x %material% in this chunk. Please remove some."

  # Message send when a user has the permission blocklimiter.check.realtime and places a tile
  # Special placeholders:
  # %tile_count%
  realtime_check: "&3Tiles: &b%tile_count%&3/&b256"

  # Message send when a user has the permission blocklimiter.check.realtime and places a custom defined block
  # Special placeholders:
  # %material%
  # %count%
  # %limit%
  realtime_check_custom: "&3%material%: &b%count%&3/&b%limit%"

  # Command messages below

  # Messages send when a user executed /blocklimiter help
  help: |-
    &8&m--------------=&r&8[&b&l BlockLimiter Help&r &8]&m=--------------
    &b /blocklimiter &f| &7Displays information about this plugin.
    &b /blocklimiter help &f| &7Displays this message.
    &b /blocklimiter reload &f| &7Reloads the plugin.
    &b /check &f| &7Displays the amount of entities & tiles in this chunk.
    &b /checkworlds &f| &7Displays the amount of entities & tiles in the server.
    &b /scan <entity|tile> &f| &7Displays a detailed message about this chunk.
    &b /scanworld <world> <entity|tile> &f| &7Displays a detailed message about a world.
    &8&m-------------------------------------------------

  # Message send when the plugin has been successfully reloaded
  reload: "&3BlockLimiter has been successfully reloaded!"

  # Message send when the plugin has been successfully reloaded
  reload_failed: "&cBlockLimiter failed to reload the config. Please check the console and report this error."

  # Message send when a user executes /check
  # Special placeholders:
  # %tile_count%
  # %entity_count%
  check: "&3There are &b&l%tile_count% &3tiles and &b&l%entity_count% &3entities in this chunk."

  # Messages send when a user executes /checkworlds
  checkworlds:
    header: "&8&m----------------=&r&8[&b&l Global Count&r &8]&m=----------------"
    # Special placeholders:
    # %world%
    # %entities%
    # %tiles%
    format: "&b %world%&8: &7&l%entities% &r&7Entities and &7&l%tiles% &r&7Tiles"
    # Special placeholders:
    # %entities%
    # %tiles%
    total: "&3 The server has a total of &b&l%entities% &3entities and &b&l%tiles% &3tiles loaded."
    footer: "&8&m-------------------------------------------------"
    none: "&cThe server has no loaded entities or tiles."

  # Messages send when a user executes /scan <entity|tile>
  scan:
    entity:
      header: "&8&m----------------=&r&8[&b&l Entity Count&r &8]&m=----------------"
      # Special placeholders:
      # %entity%
      # %count%
      format: "&b %entity%&8: &7&l%count%"
      # Special placeholders:
      # %total_count%
      total: "&3 This chunk contains a total of &b&l%total_count% &3entities."
      footer: "&8&m-------------------------------------------------"
      no_entities: "&cThe only entity this chunk has is you."
    tile:
      header: "&8&m-----------------=&r&8[&b&l Tile Count &8]&m=-----------------"
      # Special placeholders:
      # %tile%
      # %count%
      format: "&b %tile%&8: &7&l%count%"
      # Special placeholders:
      # %total_count%
      total: "&3 This chunk contains a total of &b&l%total_count% &3tile(s)."
      footer: "&8&m-------------------------------------------------"
      no_tiles: "&cThis chunk does not contain any tiles."

  # Messages send when a user executes /scan <entity|tile>
  scanradius:
    entity:
      header: "&8&m----------------=&r&8[&b&l Entity Count&r &8]&m=----------------"
      # Special placeholders:
      # %entity%
      # %count%
      format: "&b %entity%&8: &7&l%count%"
      # Special placeholders:
      # %total_count%
      total: "&3 These chunks contain a total of &b&l%total_count% &3entities."
      footer: "&8&m-------------------------------------------------"
      no_entities: "&cThe only entity these chunks have is you."
    tile:
      header: "&8&m-----------------=&r&8[&b&l Tile Count &8]&m=-----------------"
      # Special placeholders:
      # %tile%
      # %count%
      format: "&b %tile%&8: &7&l%count%"
      # Special placeholders:
      # %total_count%
      total: "&3 These chunks contain a total of &b&l%total_count% &3tile(s)."
      footer: "&8&m-------------------------------------------------"
      no_tiles: "&cThese chunks do not contain any tiles."
    invalid_number: "&cThat is not a valid number."
    invalid_radius: "&cThat radius is too big too handle for the server."

  # Messages send when a user executes /scanworld <world> <entity|tile>
  scanworld:
    entity:
      header: "&8&m----------------=&r&8[&b&l Entity Count&r &8]&m=----------------"
      # Special placeholders:
      # %entity%
      # %count%
      format: "&b %entity%&8: &7&l%count%"
      # Special placeholders:
      # %world%
      # %total_count%
      total: "&3 World &b%world% &3has a total of &b&l%total_count% &3entities."
      footer: "&8&m-------------------------------------------------"
      # Special placeholders:
      # %world%
      no_entities: "&cWorld %world% has no loaded entities."
    tile:
      header: "&8&m-----------------=&r&8[&b&l Tile Count &8]&m=-----------------"
      # Special placeholders:
      # %tile%
      # %count%
      format: "&b %tile%&8: &7&l%count%"
      # Special placeholders:
      # %world%
      # %total_count%
      total: "&3 World &b%world% &3has a total of &b&l%total_count% &3tile(s)."
      footer: "&8&m-------------------------------------------------"
      # Special placeholders:
      # %world%
      no_tiles: "&cWorld %world% has no loaded tiles."
    invalid_world: "&cThat world does not exist."

  # Messages send when a user executes /togglecheck
  togglecheck:
    # Special placeholders:
    # %name%
    enabled: "&3Realtime checking has been &benabled &3for &b%name%&3."
    # Special placeholders:
    # %name%
    disabled: "&3Realtime checking has been &bdisabled &3for &b%name%&3."

  # Message send when a user does not have a permission
  no_permission: "&cYou don't have permission to execute that command!"