name: Insights
main: net.frankheijden.insights.Insights
dev-url: https://www.spigotmc.org/resources/56489/
version: ${project.version}
softdepend: [PlaceholderAPI]
api-version: "1.13"

commands:
  insights:
    usage: 'Usage: /<command>'
    aliases:
      - 'in'

  check:
    usage: 'Usage: /<command>'

  checkworlds:
    usage: 'Usage: /<command>'

  scan:
    usage: |-
      Usage: /<command> [tile|entity|individual]
      Examples:
       /<command> tile
       /<command> entity
       /<command> custom DIAMOND_ORE
       /<command> custom DIAMOND_ORE COW

  scanradius:
    usage: |-
      Usage: /<command> <radius> [tile|entity|individual]
      Examples:
       /<command> <radius> tile
       /<command> <radius> entity
       /<command> <radius> custom DIAMOND_ORE
       /<command> <radius> custom DIAMOND_ORE COW

  scanworld:
    usage: |-
      Usage: /<command> <world> [tile|entity|individual]
      Examples:
       /<command> <world> tile
       /<command> <world> entity
       /<command> <world> custom DIAMOND_ORE
       /<command> <world> custom DIAMOND_ORE COW

  togglecheck:
    usage: 'Usage: /<command>'

permissions:
  blocklimiter.*:
    children:
      blocklimiter.check.realtime: true
      blocklimiter.reload: true
      blocklimiter.check: true
      blocklimiter.checkworlds: true
      blocklimiter.scan.*: true
      blocklimiter.scanradius.*: true
      blocklimiter.scanworlds.*: true
      blocklimiter.togglecheck.*: true

  blocklimiter.scan.*:
    children:
      blocklimiter.scan.tile: true
      blocklimiter.scan.entity: true
      blocklimiter.scan.custom.*: true
      blocklimiter.scan.tab: true

  blocklimiter.scanradius.*:
    children:
      blocklimiter.scanradius.tile: true
      blocklimiter.scanradius.entity: true
      blocklimiter.scanradius.custom.*: true
      blocklimiter.scanradius.tab: true

  blocklimiter.scanworld.*:
    children:
      blocklimiter.scanworld.tile: true
      blocklimiter.scanworld.entity: true
      blocklimiter.scanworld.custom.*: true
      blocklimiter.scanworld.tab: true