name: BlockLimiter
main: net.frankheijden.blocklimiter.BlockLimiter
dev-url: https://www.spigotmc.org/resources/56489/
version: ${project.version}
api-version: "1.13"

commands:
  blocklimiter:
    usage: 'Usage: /<command>'

  check:
    usage: 'Usage: /<command>'

  checkworlds:
    usage: 'Usage: /<command>'

  scan:
    usage: 'Usage: /<command> <tile|entity>'

  scanradius:
    usage: 'Usage: /<command> <radius> <tile|entity>'

  scanworld:
    usage: 'Usage: /<command> <world> <tile|entity>'

  togglecheck:
    usage: 'Usage: /<command>'

permissions:
  blocklimiter.*:
    children:
      blocklimiter.check.realtime: true
      blocklimiter.reload: true
      blocklimiter.check: true
      blocklimiter.checkworlds: true
      blocklimiter.scan.*: true
      blocklimiter.scanradius.*: true
      blocklimiter.scanworlds.*: true
      blocklimiter.togglecheck.*: true

  blocklimiter.scan.*:
    children:
      blocklimiter.scan.tile: true
      blocklimiter.scan.entity: true

  blocklimiter.scanradius.*:
    children:
      blocklimiter.scanradius.tile: true
      blocklimiter.scanradius.entity: true

  blocklimiter.scanworld.*:
    children:
      blocklimiter.scanworld.tile: true
      blocklimiter.scanworld.entity: true