name: Insights
main: net.frankheijden.insights.Insights
dev-url: https://www.spigotmc.org/resources/56489/
version: ${version}
softdepend: [PlaceholderAPI, WorldGuard]
api-version: "1.13"

commands:
  autoscan:
    usage: |-
      Usage: /<command> [enable|disable]
      Examples:
       /<command> entries DIAMOND_ORE CREEPER
       /<command> limit REDSTONE_WIRE
       /<command> disable

  insights:
    usage: 'Usage: /<command>'
    aliases:
      - 'in'

  check:
    usage: 'Usage: /<command>'

  checkworlds:
    usage: 'Usage: /<command>'

  scan:
    usage: |-
      Usage: /<command> [custom|entity|tile]
      Examples:
       /<command> tile
       /<command> entity
       /<command> custom DIAMOND_ORE
       /<command> custom DIAMOND_ORE COW

  scanradius:
    usage: |-
      Usage: /<command> <radius> [custom|entity|tile]
      Examples:
       /<command> <radius> tile
       /<command> <radius> entity
       /<command> <radius> custom DIAMOND_ORE
       /<command> <radius> custom DIAMOND_ORE COW

  scanworld:
    usage: |-
      Usage: /<command> <world> [custom|entity|tile]
      Examples:
       /<command> <world> tile
       /<command> <world> entity
       /<command> <world> custom DIAMOND_ORE
       /<command> <world> custom DIAMOND_ORE COW

  selection:
    usage: |-
      Usage: /<command> <create|scan|stop>
      Examples:
       /<command> create
       /<command> scan tile
       /<command> scan entity
       /<command> scan custom DIAMOND_ORE
       /<command> scan custom DIAMOND_ORE COW
       /<command> stop

  togglecheck:
    usage: 'Usage: /<command>'

  cancelscan:
    usage: 'Usage: /<command>'

permissions:
  insights.*:
    children:
      insights.check.realtime: true
      insights.reload: true
      insights.check: true
      insights.checkworlds: true
      insights.scan.*: true
      insights.scanradius.*: true
      insights.scanworlds.*: true
      insights.togglecheck.*: true

  insights.scan.*:
    children:
      insights.scan.tile: true
      insights.scan.entity: true
      insights.scan.custom.*: true
      insights.scan.all: true
      insights.scan.tab: true

  insights.scanradius.*:
    children:
      insights.scanradius.tile: true
      insights.scanradius.entity: true
      insights.scanradius.custom.*: true
      insights.scanradius.all: true
      insights.scanradius.tab: true

  insights.scanworld.*:
    children:
      insights.scanworld.tile: true
      insights.scanworld.entity: true
      insights.scanworld.custom.*: true
      insights.scanworld.all: true
      insights.scanworld.tab: true