settings:
  concurrent-scan-threads: -1
  chunk-scan-mode: "MODIFICATION"
  progress-notification:
    type: "BOSSBAR"
    bossbar:
      color: "BLUE"
      style: "SEGMENTED_10"
      flags: []
      duration-ticks: 60
  worldedit-integration:
    enabled: true
    type: "REPLACEMENT"
    replacement-block: "BEDROCK"
