settings:
  update-checker:
    enabled: true
    interval-seconds: 10800
  scans:
    concurrent-threads: -1
    iteration-interval-ticks: 1
    chunks-per-iteration: 256
    info-interval-millis: 100
  chunk-scans:
    mode: "ALWAYS"
    player-tracker-interval-ticks: 5
  notification:
    type: "BOSSBAR"
    bossbar:
      color: "BLUE"
      style: "SEGMENTED_10"
      flags: []
      duration-ticks: 60
    actionbar:
      segments: 50
      progress-sequence: "|"
      done-color: "&a"
      total-color: "&8"
      separator: " "
  spigot:
    entity-tracker-interval-ticks: 10
  apply-piston-limits: true
  disabled-listeners:
    - "BlockFromToEvent"
    - "FluidLevelChangeEvent"
    - "SpongeAbsorbEvent"
    - "LeavesDecayEvent"
