name: Java CI with Gradle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 16 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java-version }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: actions/cache@v2
        with:
          path: |
            ~/**/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        run: ./gradlew clean build --stacktrace
      - name: Upload artififacts
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Insights
          path: jars/*.jar
